Traceback (most recent call last):
  File "/sec/securify/grammar/attributes/evaluators/evaluator_demand_iterative.py", line 53, in evaluate
    result = super()._execute_rule(rule, arguments)
  File "/sec/securify/grammar/attributes/evaluators/evaluator_base.py", line 42, in _execute_rule
    return rule.func(**{name: node for name, node in arguments.items()})
  File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 261, in contract_cfg_unlinked
    cfgs = {node.id: build_function_cfg(node.cfg) for node in cfgs if node.implemented}
  File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 261, in <dictcomp>
    cfgs = {node.id: build_function_cfg(node.cfg) for node in cfgs if node.implemented}
  File "/sec/securify/ir/cfgutils.py", line 232, in build_function_cfg
    successor = cfg_simple.successor(successor)
  File "/sec/securify/ir/cfgutils.py", line 26, in successor
    return single_element(self.graph.successors(element), or_else)
  File "/sec/securify/ir/cfgutils.py", line 305, in single_element
    raise ValueError("Set contains more than one element."
ValueError: Set contains more than one element.Cannot select successor unambiguously from: 
    Block(ast_node=<securify.grammar.attributes.evaluators.evaluator_demand_base.IfStatement__AllAttrsMixin object at 0x7f8741d56090>)
    TIMESTAMP(ast_node=<securify.grammar.attributes.evaluators.evaluator_demand_base.Identifier__AllAttrsMixin object at 0x7f8741d5e4d0>, variable='TIMESTAMP', type_string='uint256')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "securify/__main__.py", line 286, in <module>
    main()
  File "securify/__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/sec/securify/analyses/patterns/static/static_analysis_patterns.py", line 73, in find_matches
    static = analysis_context.static_analysis
  File "/sec/securify/analyses/analysis.py", line 88, in static_analysis
    self._static = self.config.static_analysis(self)
  File "securify/__main__.py", line 255, in <lambda>
    static_analysis=lambda t: static_analysis.analyze_cfg(t.cfg, **souffle_config),
  File "/sec/securify/analyses/analysis.py", line 81, in cfg
    self._cfg = self.config.cfg_compiler(self)
  File "securify/__main__.py", line 254, in <lambda>
    cfg_compiler=lambda t: solidity_cfg_compiler.compile_cfg(t.ast).cfg,
  File "/sec/securify/solidity/solidity_cfg_compiler.py", line 88, in compile_cfg
    cfg = ast_attr.cfg
  File "/sec/securify/grammar/attributes/evaluators/evaluator_demand_base.py", line 84, in __get__
    return self.__evaluator.evaluate(instance, self.__name)
  File "/sec/securify/grammar/attributes/evaluators/evaluator_demand_iterative.py", line 57, in evaluate
    f"Rule trace: {self.__rule_trace(dependency_path)}") from e
securify.grammar.attributes.AttributeGrammarError: Error during evaluation of rule 'contract_cfg_unlinked'. 
Rule trace: 
	SynthesizeRule cfg (File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 199)
	SynthesizeRule cfg (File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 272)
	PushdownRule next_cfgs_unlinked (ImplicitPushdown)
	PushdownRule next_cfgs_unlinked (ImplicitPushdown)
	PushdownRule next_cfgs_unlinked (ImplicitPushdown)
	PushdownRule push_cfgs (File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 163)
	SynthesizeRule contract_cfg_unlinked (File "/sec/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 258)

---------------------------------------------
For contract 0x34194a17d9d02bdabe930b27919ce797cfb065bf.sol
Tool Runtime = 1.8281153879997873 seconds
#############################################